Instructor feedback
mishelshaji/EXP-G6-ELearningPortal pull request #21
Opened 2023-02-17 05:26 UTC by VARSHAV2001

2023-02-17 05:51 UTC, mishelshaji requested changes

2023-02-17 05:51 UTC, mishelshaji commented on client/src/assets/style.css
> +    background-color: white;
Use color value instead.

2023-02-17 05:51 UTC, mishelshaji commented on client/src/assets/style.css
> +     background-color: white;
Use color value instead.

2023-02-17 05:51 UTC, mishelshaji commented on client/src/assets/style.css
> + .feedback-main-body{
Format the code.

2023-02-17 07:02 UTC, VARSHAV2001 commented on client/src/assets/style.css
> +    background-color: white;
Issue resolved

2023-02-17 07:02 UTC, VARSHAV2001 commented on client/src/assets/style.css
> +     background-color: white;
Issue resolved

2023-02-17 07:02 UTC, VARSHAV2001 commented on client/src/assets/style.css
> + .feedback-main-body{
Issue resolved

2023-02-17 07:36 UTC, mishelshaji approved these changes

2023-02-18 06:20 UTC, mishelshaji requested changes

2023-02-18 06:20 UTC, mishelshaji commented on client/src/App.js
>  import StudentProfile from './pages/student/StudentProfile';
Format and group routes.

2023-02-18 07:07 UTC, VARSHAV2001 commented on client/src/App.js
>  import StudentProfile from './pages/student/StudentProfile';
formatted

2023-02-18 09:25 UTC, mishelshaji approved these changes

2023-02-18 09:25 UTC, merged