created order page
mishelshaji/EXP-G6-ELearningPortal pull request #8
Opened 2023-02-13 05:29 UTC by VARSHAV2001

2023-02-13 08:19 UTC, mishelshaji requested changes

2023-02-13 08:19 UTC, mishelshaji commented on client/src/pages/student/Order.js
> +      <NavigationBar />
Why don't you use a layout instead?

2023-02-13 08:19 UTC, mishelshaji commented on client/src/pages/student/Order.js
> +                  <img src={data.img} alt="" className="img-thumbnail" />
Give a value for the alt attribute.

2023-02-14 10:26 UTC, mishelshaji approved these changes

2023-02-14 10:27 UTC, VARSHAV2001 commented on client/src/pages/student/Order.js
> +                  <img src={data.img} alt="" className="img-thumbnail" />
given value for alt attribute

2023-02-14 10:46 UTC, mishelshaji commented
Did you forget to commit changes?

2023-02-14 12:35 UTC, mishelshaji approved these changes

2023-02-14 12:36 UTC, merged